Прочитать про методы оптимизации для нейронных сетей https://habr.com/post/318970/

Реализовать самостоятельно логистическую регрессию

Обучить ее методом градиентного спуска
Методом nesterov momentum
Методом rmsprop


В качестве dataset’а взять Iris, оставив 2 класса:
Iris Versicolor
Iris Virginica

In [243]:
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
import pandas as pd
import numpy as np
import seaborn as sns

In [244]:
iris = load_iris()

In [245]:
idx = iris.target != 0
X = iris.data[idx].astype(np.float32)
Y = iris.target[idx].astype(np.float32)

In [270]:
# размер данных
m, n = np.shape(X)

In [271]:
X = np.c_[ np.ones(m), X]

In [272]:
# шаг алгоритма
alpha = 0.001

In [313]:
def gradient_descent(alpha, x, y, numIterations):
    """
    Функция реализует алгоритм градиентного спуска для логистической регрессии.
    
    """
    m = x.shape[0] 
    theta = np.ones(x.shape[1])
    x_transpose = x.transpose() 
    
    for iter in range( 0, numIterations ):
        hypothesis = 1 / (1 + np.exp(-np.dot(x, theta)))
        epsilon = 1e-5
        loss = hypothesis - y
        J = (1/m)*np.sum(y * np.log(hypothesis + epsilon) - (1 - y) *np.log(1 - hypothesis + epsilon))
        gradient = np.dot(x_transpose, loss) /  m 
        theta = theta - alpha * gradient
    
    return theta

In [314]:
%%time
theta = gradient_descent(alpha, X, Y, 10000)
theta

Wall time: 272 ms


array([ 6.00000001, 33.94000006, 15.86999998, 28.75999998, 11.1299999 ])

In [315]:
def get_minibatch(X, y, minibatch_size):
    minibatches = []

    X, y = shuffle(X, y)

    for i in range(0, X.shape[0], minibatch_size):
        X_mini = X[i:i + minibatch_size]
        y_mini = y[i:i + minibatch_size]

        minibatches.append((X_mini, y_mini))

    return minibatches

In [316]:
def gradient(x, y, theta):
    m = x.shape[0] 
    x_transpose = x.transpose() 
    hypothesis = 1 / (1 + np.exp(-np.dot(x, theta)))
    epsilon = 1e-5
    loss = hypothesis - y
    J = (1/m)*np.sum(y * np.log(hypothesis + epsilon) - (1 - y) *np.log(1 - hypothesis + epsilon))
    gradient = np.dot(x_transpose, loss) /  m  
    
    return gradient

In [427]:
def nesterov(X, y, alfa, n_iter):
    v0 = np.zeros(X.shape[1])
    gamma = 0.9
    theta0 = np.ones(X.shape[1]) 

    for iter in range(1, n_iter + 1):
        grad = gradient(X, y, theta0)
        vk = gamma*v0 + alfa*grad
        thetak = theta0 - vk
        v0 = vk
        theta0 = thetak
        
    return thetak

In [430]:
%%time
theta = nesterov(X,Y, alpha, 1000)
theta

Wall time: 26.1 ms


array([ 5.95500002, 33.64354013, 15.73617001, 28.51016003, 11.03882992])

In [472]:
def rmsprop(X, y, alfa, n_iter):
    v0 = np.ones(X.shape[1])
    gamma = 0.9
    theta0 = np.ones(X.shape[1])
    epsilon = 1e-5
    
    for iter in range(1, n_iter + 1):
        grad = gradient(X, y, theta0)
        vk = gamma * v0 + (1 - gamma) * (grad**2)
        thetak = theta0 - alfa * grad /(np.sqrt(vk + eps))
        v0 = vk
        theta0 = thetak
        
    return thetak

In [473]:
%%time
theta = rmsprop(X,Y, alpha, 200)
theta

Wall time: 6.99 ms


array([1.19255163, 1.20711243, 1.20315903, 1.20650876, 1.20011581])